### PR TITLE
Gate tagging support

### PR DESCRIPTION
**Pull request by rschatz**
Based on #42. I'm doing this on top of the other pull request to save a version bump.

This adds a special tag `always` that's always implicitly included.

For example:
`mx -v gate --dry-run --tags build`
```
Gate task times:
  0:00:00.000013        Versions [always]
  0:00:00.000018        JDKReleaseInfo [always]
  0:00:00.000018        Clean [build,style]
  0:00:00.000016        BuildJavaWithJavac [build,style]
  =======
  0:00:00.000420
```

It can still be explicitly excluded:
`mx -v gate --dry-run --tags always,style -x`
```
Gate task times:
  0:00:00.000018        Clean [build,style]
  0:00:00.000016        BuildJavaWithJavac [build,style]
  =======
  0:00:00.000294
```

### CODE REVIEW

**Comment by zapster** [comment]
looks good to me but since it contains changes by myself I'd like a second review. maybe @dougxc

**Comment by dougxc** [comment]
I'm happy to merge this but assume I need to wait for #42 to be merged first?

**Comment by zapster** [comment]
no, we can just merge it as it contains all changes from #42. #42 can then be close.

**Comment by rschatz** [comment]
That's actually what I want to try out here. I think #42 should automatically close when we merge this. We'll see how github deals with this ;)

**Pull request merged**
