### PR TITLE
[Refactoring] Add and use individual platform checks

### PR DESCRIPTION
**Pull request by fniephaus**
Title says it all.

### CODE REVIEW

**Comment by dougxc** [comment]
Looks like a nice improvement. Once you've fixed the Travis tests, I'll integrate it.

**Comment by fniephaus** [comment]
Whoops, `is_linux()` went missing for some reason. Fixed it!

**Comment by fniephaus** [comment]
Oh dear,  it looks like [Travis](https://www.traviscistatus.com/incidents/rxz57n2f96f6) and [GitHub](https://www.githubstatus.com/incidents/tj58y1kx7tqy) both have issues at the moment. 🧐

**Comment by dougxc** [comment]
Integrated as https://github.com/graalvm/mx/commit/e20f0cdf74ebec224f9738d85cb0c4017493dd9f.

**Pull request closed without merging**
