### PR TITLE
Fix --tags ranges regex

### PR DESCRIPTION
**Pull request by zakkak**

### CODE REVIEW

**Comment by dougxc** [comment]
Looks good - merging now.

**Comment by dougxc** [comment]
@zapster pointed out that the current implementation matches what the documentation says:
```
  --tags TAGS           comma separated list of tags to select subset of tasks
                        to be run. Tags can have a range specifier
                        `name[:from:[to]]`.If present only the [from,to) tasks
                        are executed. If `to` is omitted all tasks starting
                        with `from` are executed.
```

That is, `--tags:style:4:` is the way to specify "all style tasks starting at the 4th".

**Comment by zakkak** [comment]
I might need to increase my font size (or retrain my brain) :D

Thanks @zapster for catching this.

**Comment by zapster** [comment]
@zakkak I also had to look at the regex and the --help message a few times before noticing it. :)

**Pull request closed without merging**
