### PR TITLE
Add TestNG support.

### PR DESCRIPTION
**Pull request by christhalinger**
SQE is adding some new JVMCI tests and is using TestNG.  I want them to integrate the new tests with mx.

### CODE REVIEW

**Comment by dougxc** [comment]
This is just adding the TestNG library to mx without any command for running TestNG tests. It would make more sense to add the library to the mx suite that includes TestNG based sources and (possibly) has an mx extension command for running them.

**Comment by christhalinger** [comment]
Yeah, I noticed that as well after I was poking around in the new tests.  ``unittest`` should support running TestNG tests.  I'm looking into it right now.

**Comment by dougxc** [comment]
Christian, are you still looking into modifying the `unittest` command or can I close this issue as won't fix?

**Comment by christhalinger** [comment]
I was wondering about this myself :)  At this point I don't care, so we can close it.

**Pull request closed without merging**
