### PR TITLE
Fix os.path.relpath throwing

### PR DESCRIPTION
**Pull request by JornVernee**
Replaced calls to os.path.relpath with a safe alternative, since not every path can be made relative on Windows, due to different drives.

This is based on another PR [1], where the author asked someone else to take over since they don't have time to fix the merge conflicts [2].

~I tried running `mx gate`  but that throws an unrelated error, so it doesn't look like that works on Windows yet. So be aware that this has not passed gate yet.~

[1] : https://github.com/graalvm/mx/pull/134
[2] : https://github.com/graalvm/mx/pull/134#issuecomment-436805868

### CODE REVIEW

**Comment by JornVernee** [comment]
I have already signed the OCA: https://openjdk.java.net/census#jvernee

**Comment by JornVernee** [comment]
Hey Doug,

Just to make sure I'd like to wait for the old author to give the OK before merging this.

It seems like they have abandoned their own PR, and don't really care, but they _did_ come up with the fix after all.

**Comment by dougxc** [comment]
I think we're fine to proceed based on @okutane 's [comment](
https://github.com/graalvm/mx/pull/134#issuecomment-436805868).

**Comment by JornVernee** [comment]
@dougxc Ok, then go ahead.

**Comment by gilles-duboscq** [comment]
Hi @JornVernee, thanks for taking a stab at this.
Unfortunately we can not simply replace `os.path.relpath` with `maybe_relpath`. I would actually say that we can only do it in rare cases.

In particular, there are cases where the logic simply doesn't work if a relative path can not be created, in those it needs to remain an error and the root case has to be fixed.

In many cases it's OK anyway because relapth is used in conditions where a relative path can always be found (in particular when using `os.walk`).

In other cases, a more complex logic is needed. For example in intellij project generation, when a relative path can be found, the `$PROJECT_DIR$` variable should be used and if it can not then an absolute path should be used.

In other places a unix path is used as a short-cut to something else (a relative URL, a logical path in an archive etc.) and an other platform-independent approach should be used.

In order to make progress, I propose that we don't fix everything at once but just fix the ones where `maybe_relpath` can be used and the `intellijinit` ones since that was the purpose of the original PR.

**Comment by JornVernee** [comment]
I see travis is running `mx gate` in strict mode.

When doing that myself I get:
```
require pylint version = 1.1.x (got 1.8.4)
Pylint not configured correctly. Cannot execute Pylint task.
```
Should that requirement be bumped up to 1.x.x ?

**Comment by JornVernee** [comment]
I have successfully run `mx ideinit` on the graal/compiler suite. I also tried the vm suite, but that failed due to an unrelated error.

**Comment by JornVernee** [comment]
I think I/we will have to look into this some more. One other problem I realized is that the paths are sometimes used as URLs, for which they must use `/` as a path separator. On unix that just works out when using normal paths, but on Windows it does not.

**Comment by JornVernee** [comment]
I looked into this and decided to keep the changes simple, @gilles-duboscq or @dougxc  can you take another look? I pushed the relpath lookup into make_library so it can either use `$PROJECT_DIR$` or an absolute path. (I squashed all my commits, so the commit message looks a bit strange)

I was able to pass `mx build` on the graal/compiler suite and run it with `mx vm` so that's 👍 . I also ended up fixing #165 in the process (a regex that wasn't matching on Windows path separators).

**Comment by gilles-duboscq** [comment]
> Any idea where I can get the right version of pylint?
```
$ pip install 'astroid==1.1.0'
$ pip install 'pylint==1.1.0'
```
(You have to install strict versions and install astroid first with a strict version although it's an explicit dependency of pylint)

**Pull request merged**
