### PR TITLE
[GR-37095] Adds ability to create jar entries for directories

### PR DESCRIPTION
**Pull request by zakkak**
Just create an `.mxkeep` file in a directory and any jar distribution
containing this directory will include a jar entry for it. The `.mxkeep`
file will not be included.

### CODE REVIEW

**Comment by zakkak** [comment]
@gilles-duboscq @olpaw please review.
I followed the `.gitkeep` convention and used `.mxkeep` instead of `.empty_dir`.

**Review by olpaw — APPROVED** [review]

**Review by olpaw — CHANGES_REQUESTED** [review]
LGTM

Please also update
```
version = VersionSpec(...
```
accordingly in an additional commit.
(Search for `# The version must be updated for every PR (checked in CI)` in `mx.py`)

**Comment by zakkak** [comment]
> Please also update
> 
> ```
> version = VersionSpec(...
> ```
> 
> accordingly in an additional commit. (Search for `# The version must be updated for every PR (checked in CI)` in `mx.py`)

What should I add as the PR reference next to the version? `GH-256`?

**Comment by olpaw** [comment]
> > What should I add as the PR reference next to the version? [GH-256](https://github.com/graalvm/mx/pull/256)?
> 
> Yes, that should work. Thanks!

Even better, use GR-37095 (see https://github.com/graalvm/mx/pull/256#event-6118597638)

**Comment by zakkak** [comment]
Done :)

**Comment by dougxc** [comment]
@olpaw @fniephaus it's usually better to update `version` with a separate commit in the internal PR used to integrate a GitHub PR. That way, an external committer does not have to try "win" the version bump race.

**Comment by olpaw** [comment]
> @olpaw @fniephaus it's usually better to update `version` with a separate commit in the internal PR used to integrate a GitHub PR. That way, an external committer does not have to try "win" the version bump race.


I see. If there is a conflict I will replace @zakkak version update commit with my own.

**Comment by dougxc** [comment]
For reference, the motivation for this change is here: https://github.com/oracle/graal/pull/4327#issuecomment-1047028246

**Comment by olpaw** [comment]
Merged as https://github.com/graalvm/mx/commit/39ac3b71912af1edf04f7413adf36a74550c09bb

**Pull request closed without merging**
