### PR TITLE
Support for musl-based Linux

### PR DESCRIPTION
**Pull request by petermz**
A couple of fixes related to musl-based Linux support:
* Changed the order in which OS attributes are examined: most specific variant should come first, e.g. `linux-musl`, then `linux`, then `<others>`
* Added `-Wno-error=cpp` for `linux-musl` so that it doesn't complain about nonstandard headers such as `<sys/errno.h>`

This is needed to take advantage of https://github.com/oracle/graal/pull/3141

### CODE REVIEW

**Comment by gilles-duboscq** [comment]
Wouldn't it be better to include `<errno.h>`?
/cc @tkrodriguez

**Comment by petermz** [comment]
They should be interchangeable on Linux (same for poll.h, signal.h etc), but I'm not sure about Windows and Darwin

**Comment by gilles-duboscq** [comment]
Looks like that should be fine for [Windows](https://learn.microsoft.com/en-us/cpp/c-runtime-library/errno-constants?view=msvc-170) and a quick check on a macOS machine shows that it has `/usr/include/errno.h` (and `/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/errno.h`)

**Review by gilles-duboscq — APPROVED** [review]

**Comment by gilles-duboscq** [comment]
I'll start integrating that. I'll take care of bumping the mx version number.

**Comment by gilles-duboscq** [comment]
You can now depend on the updated behaviour by requesting a minimal mx version of 6.15.0

**Pull request merged**
