### PR TITLE
Upgrade to JaCoCo 0.8.2 (with support for JDK8-12)

### LINKED ISSUE #154: Upgrade JaCoCo dependency
Since [`v0.8.1`](https://github.com/jacoco/jacoco/releases/tag/v0.8.1), JaCoCo supports Java 10 and therefore, it'd be nice if the mx dependency could be updated at some point.

### PR DESCRIPTION
**Pull request by fniephaus**
I have tested this with GraalSqueak on JDK8 and JDK11 and it seems to work fine so far.

JaCoCo change history: https://www.jacoco.org/jacoco/trunk/doc/changes.html

This is an updated version of #155 and fixes #154.

/cc @dougxc

### CODE REVIEW

**Comment by dougxc** [comment]
Hi @fniephaus , thanks for the PR! If you can make the changes I [requested](
https://github.com/graalvm/mx/pull/155#discussion_r200919735) initially, then I will sponsor this PR.

**Comment by dougxc** [comment]
I realized there is no mention of how to use JaCoco in `README.md`. It would be great if you could consider adding a `Using JaCoCo` section to that document as part of this PR.

**Comment by fniephaus** [comment]
Hi @dougxc, I've made the changes you requested previously. However, I noticed the way libraries are versioned is inconsistent (underscores vs dots). Also, I've added a subsection on how to do coverage testing with mx and JaCoCo. Please let me know if further changes are necessary.

**Comment by dougxc** [comment]
Thanks for making the changes and updating the README. There is indeed some inconsistency in the versioning format but we have to live with both so your choice is fine.
Once I get internal approvals for this new version of JaCoCo, I'll integrate your PR.

**Comment by fniephaus** [comment]
Thanks!

**Comment by fniephaus** [comment]
Hey @dougxc, any news on this?

**Comment by dougxc** [comment]
Sorry @fniephaus , still waiting for approval process to complete.

**Comment by dougxc** [comment]
Resolved by https://github.com/graalvm/mx/commit/4dbbbbb3fe476b30dc4ea647c63551bde7909768.

**Pull request closed without merging**
