### PR TITLE
Make `mx fetch-jdk` python2 compatible

### LINKED ISSUE #238: mx fetch-jdk failure with python2
Running `mx fetch-jdk` without setting `MX_PYTHON` or `MX_PYTHON_VERSION` results in the following failure.

```
$ git clone --depth 1 git@github.com:graalvm/mx
$ ./mx/mx fetch-jdk --jdk-id openjdk8 --to jdk-dl
/tmp/mx/common.json -> "jdks" -> "oraclejdk16" -> "version": value (16.0.1+4) must be a str, not a unicode
```

### PR DESCRIPTION
**Pull request by zakkak**
Closes #238

### CODE REVIEW

**Comment by dougxc** [comment]
Hi @zakkak , we are close to removing all python2 support from mx so this is going in the wrong direction.

**Comment by zakkak** [comment]
Thanks Doug, good to know!

**Comment by dougxc** [comment]
Turns out that there's enough people still relying on `fetch-jdk` to work with python2 so I'll merge this fix after all.

**Comment by zakkak** [comment]
Merged in https://github.com/graalvm/mx/commit/fe5916d4eaeae8d7e4548b58a90a7105798806fb

**Pull request closed without merging**
