### PR TITLE
support project javaCompliance value that ends with "+" as a lower bound

### PR DESCRIPTION
**Pull request by dougxc**
Fixes this issue:
```
SystemExit: dependency named com.oracle.mxtool.compilerserver was not found:
  project com.oracle.mxtool.compilerserver was removed as Java compliance 1.7 cannot be satisfied by configured JDKs
```

### CODE REVIEW

**Comment by tkrodriguez** [comment]
looks good

**Comment by gilles-duboscq** [comment]
Is it something like "higher is better even if `--strict-compliance` is enabled"?

**Comment by dougxc** [comment]
No, it currently selects the first compatible JDK. I don't see a need for anything more specific than that.

**Pull request merged**
