### PR TITLE
Group classes by function or type 2 iteration

### PR DESCRIPTION
**Pull request by neomatrix369**
Please merge #196 before merging this.

Reorganised blocks of code belonging to these categories:
    - OS/Arch/System
    - Distribution
    - Language Support
    - _private functions 

Build status: [CircleCI](https://circleci.com/gh/neomatrix369/awesome-graal/tree/build-mx-from-another-repo)

### CODE REVIEW

**Comment by dougxc** [comment]
FYI: There may be some delays merging these mx PRs and we have some issues with downstream failures in our internal gates.

**Comment by neomatrix369** [comment]
> FYI: There may be some delays merging these mx PRs and we have some issues with downstream failures in our internal gates.

No worries, I'll park them here for review when they are ready to be merged.

Downstream failures - are they caused by #196 or #197? Is there a way we can test for them beforehand?

**Comment by dougxc** [comment]
I don't think they are related to #196 or #197. These are tests against GraalVM EE so there's no way expose them here.

**Comment by neomatrix369** [comment]
I'll get around fixing this failing build and branch conflict asap!

**Comment by neomatrix369** [comment]
@dougxc And this one as well, they keep going out of sync as `master` is always moving

**Comment by dougxc** [comment]
@neomatrix369 please rebase this PR on master (squashing out the merge commits if possible in the process) before I start trying to integrate it.

**Comment by neomatrix369** [comment]
> @neomatrix369 please rebase this PR on master (squashing out the merge commits if possible in the process) before I start trying to integrate it.

Just done, squashed all commits into a single one and remove the merge commits - does this work for you?

**Comment by dougxc** [comment]
I'd like to delay integrating this PR until you're confident that it's the last big reshuffling of code in `mx.py`. Such huge code movements kill any existing PR, patch, local branches etc. and so should be minimized.

**Comment by dougxc** [comment]
Please use Gilles' [script](https://github.com/graalvm/mx/pull/196#issuecomment-508497812) to prepare a more reviewable set of diffs for this PR.

**Comment by neomatrix369** [comment]
> Please use Gilles' [script](https://github.com/graalvm/mx/pull/196#issuecomment-508497812) to prepare a more reviewable set of diffs for this PR.

Will do.

**Comment by neomatrix369** [comment]
> I'd like to delay integrating this PR until you're confident that it's the last big reshuffling of code in `mx.py`. Such huge code movements kill any existing PR, patch, local branches etc. and so should be minimized.

I'm not expecting big PRs like this hereafter, this shuffle was necessary in some ways. The next ones should be more focussed and smaller. I agree it leads to difficulties.

**Comment by neomatrix369** [comment]
@dougxc just applied it on `mx.py`, would you like me to push this back into the PR branch? The script created a folder called `mx.py_cut` with about 385 files corresponding to each declaration. 

I'll push these files into the branch, you can review and comment on them, I'll apply the fixes to `mx.py` (if any) and before we merge we can remove this folder. Is this how you would like this to work?

@gilles-duboscq I'm guessing these files are only reference purposes when reviewing the code? We won't merge them back into `mx.py`?

**Comment by dougxc** [comment]
Just create a gist of the diff between the 2 directories created by the script.

**Comment by neomatrix369** [comment]
> Just create a gist of the diff between the 2 directories created by the script.

https://gist.github.com/neomatrix369/f5989ef61d1cdf0ad7b896a2d4c183cf Is this good?

**Comment by neomatrix369** [comment]
> Please use Gilles' [script](https://github.com/graalvm/mx/pull/196#issuecomment-508497812) to prepare a more reviewable set of diffs for this PR.

I feel there is room for automation such that each time we have a big PR, these two scripts (@gilles-duboscq's and mine) kick in and create a gist or diff file for the reviewer to glance - we won't need each developer opening the PR to do this manually. This is a separate discussion on its own and will require some GitHub post action hooks to be triggered, its possible to do it via GitHub actions by the way.

/cc @gilles-duboscq

**Comment by dougxc** [comment]
Your gist is good enough although the formatting is not the usual output I would expect from `diff <dir1> <dir2>`. I don't think there's a need to automate this as I expect such large changes of the nature (i.e. mostly pure reorganization) to be very rare.

**Comment by dougxc** [comment]
Let me know when this PR is ready for integration.

**Comment by neomatrix369** [comment]
> Your gist is good enough for reviewing purposes although the formatting is not the usual output I would expect from `diff <dir1> <dir2>`. I don't think there's a need to automate this as I expect such large changes of the nature (i.e. mostly pure reorganization) to be very rare.

I did a file/file comparison and used these additional flags: `--suppress-common-lines -y -d --strip-trailing-cr`

I have updated the gist now, let me know if this works for you.

**Comment by dougxc** [comment]
I find the output of `diff -u <dir1> <dir2>` is easiest to read although that's just a matter of personal preference.
I'll integrate this PR in the next few days.

**Comment by neomatrix369** [comment]
> I find the output of `diff -u <dir1> <dir2>` is easiest to read although that's just a matter of personal preference.
> I'll integrate this PR in the next few days.

Indeed that looks pretty close to git diff - I have updated the gist, thanks for taking this forward.

**Comment by gilles-duboscq** [comment]
I agree with the overall goal of splitting up `mx.py` but can we keep the number of iterations on this rather low? This kind of changes that just moves things around make any patch, branch, PR etc. extremely hard to merge or rebase.

**Comment by dougxc** [comment]
@neomatrix369 please confirm there are no more large reshufflings in the pipeline before I start to integrate this PR.

**Comment by neomatrix369** [comment]
> @neomatrix369 please confirm there are no more large reshufflings in the pipeline before I start to integrate this PR.

None that I know of, I tried to squeeze in all the shuffling in #196 and #197 so that future PRs are easier to make and also cause fewer movements. Please go ahead with integrating.

**Comment by neomatrix369** [comment]
> I agree with the overall goal of splitting up `mx.py` but can we keep the number of iterations on this rather low? This kind of changes that just moves things around make any patch, branch, PR etc. extremely hard to merge or rebase.

I have this in mind and will try to keep such moves to the minimum.

**Comment by neomatrix369** [comment]
@dougxc all fine with the PR from yourside? From my side, it's good to go and no more big changes.

**Comment by dougxc** [comment]
This has already been merged in https://github.com/graalvm/mx/commit/f2e842f70424a64a775d32f39ae0554f66c2f080.

**Comment by neomatrix369** [comment]
> This has already been merged in [f2e842f](https://github.com/graalvm/mx/commit/f2e842f70424a64a775d32f39ae0554f66c2f080).

Ok cool, shall we close this PR then?

**Comment by dougxc** [comment]
Yes please.

**Pull request closed without merging**
